include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
  exclude:
    - lib/**.*.dart
linter:
  rules:
    - avoid_void_async
    - directives_ordering
    - prefer_relative_imports
    - sort_pub_dependencies
